config/routes.rb
  get '/questions/:id/friends' => 'questions#show_friends', as: :question_friends
  get '/questions/:id/general' => 'questions#show_general', as: :question_general
  get '/questions/import_all' => 'questions#import_all', as: :import_all_questions
  get '/questions/import_new' => 'questions#import_new', as: :import_new_questions
  resources :questions, only: [:index, :show]

  # Comment
  resources :comments, only: [:create, :destroy] 

  # Reply
  resources :replies, only: [:create, :destroy]

  # Like
  resources :likes, only: [:create, :destroy]
  get '/likes/:target_type/:target_id' => 'likes#likes_info'

  # Assignment
  get '/assignments' => 'assignments#index', as: :assignments
  get '/assignments/:question_id' => 'assignments#new', as: :new_assignment
  post '/assignments/:assignee_id/:question_id' => 'assignments#create', as: :create_assignment # get?
  delete '/assignments/:assignee_id/:question_id' => 'assignments#destroy', as: :destroy_assignment
  post '/assignments/:assignee_id/custom_question/:custom_question_id' => 'assignments#create_custom', as: :create_custom_assignment # get?
  delete '/assignments/:assignee_id/custom_question/:custom_uestion_id' => 'assignments#destroy_custom', as: :destroy_custom_assignment
  get '/assignments/custom_question/:custom_question_id' => 'assignments#new_custom', as: :new_custom_assignment

  # Drawer
  resources :drawers, only: [:create, :destroy]
  get '/drawers/:target_type/:target_id' => 'drawers#drawers_info'

  # Highlight
  resources :highlights, only: [:create, :destroy]

  # Notification
  get '/notifications' => 'notifications#index' , as: :notifications
  get '/notifications/read_all' => 'notifications#read_all', as: :notification_read_all
  get '/notifications/:id' => 'notifications#read'

  # Profile
  get '/profiles/:id' => 'profiles#index', as: :profile
  get '/profiles/:id/drawers' => 'profiles#drawers', as: :profile_drawers

  # User
  get '/users/:id/edit' => 'users#edit', as: :edit_user_profile
  patch '/users/:id/edit' => 'users#update', as: :update_user_profile
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', :confirmations => 'users/confirmations', :passwords => 'users/passwords', :sessions => 'users/sessions' }
  # 아래 코드는 이후에 멀티채널 구성에 맞추어 바뀌어야할수도.
  get '/users/friends' => 'users#friends', as: :friends
  put '/users/:id/image_upload' => 'users#image_upload', as: :image_upload
  # put '/users/:id/upload_image' => 'users#update', as: :upload_image
  post '/users/:id/add_friend' => 'users#add_friend', as: :add_friend # get?
  post '/users/:id/delete_friend' => 'users#delete_friend', as: :delete_friend
  # post '/users/:id/friend_request' => 'users#friend_request', as: :friend_request_send # get?
  
  # FriendRequest
  resources :friend_requests, only: [:destroy]
  get '/friend_requests' => 'friend_requests#index', as: :friend_requests
  post '/friend_requests/:id' => 'friend_requests#create', as: :friend_request_create
  put '/friend_requests/:id/deny' => 'friend_requests#deny', as: :friend_request_deny

  # Invitation
  get '/invitations' => 'invitations#index', as: :invitations
  get '/invitations/link' => 'invitations#link', as: :invitation_link
  get '/invitations/:id(/:question_id1(/:question_id2(/:question_id3)))' => 'invitations#accept', as: :invitation_accept

  # Search
  get '/search/all' => 'search#all', as: :search_all
  get '/search/admin_question' => 'search#admin_question', as: :search_admin_question
  get '/search/custom_question' => 'search#custom_question', as: :search_custom_question
  get '/search/user' => 'search#user', as: :search_user

  # Channel
  resources :channels, only: [:create, :update, :destroy]
  put '/channels/:id/edit_friendship' => 'channels#edit_friendship'

  # Announcement
  resources :announcements, only: [:create, :update, :destroy]
  get '/announcements' => 'announcements#index', as: :announcement_index
  get '/announcements/admin'  => 'announcements#admin_index', as: :announcement_admin_index
  get '/announcements/:id/publish' => 'announcements#publish', as: :announcement_publish
  get '/announcements/:id/noti' => 'announcements#noti', as: :announcement_noti

  # User Stats
  get '/stats/daily' => 'stats#daily', as: :daily_stats
  get '/stats/monthly' => 'stats#monthly', as: :monthly_stats
  
  namespace 'api' do
    namespace 'v1', defaults: { format: :json } do
      
      # Sessions
      resource :sessions, only: [:create, :destroy, :show] # delete request가 실제로 user을 delete하는 것이 아니기 때문에 resources가 아니라 resource로 두는 것이 맞습니다. 고치지 말아주세요!
      resources :users, only: [:create] 

      # Answer
      resources :answers, except: [:new]
      get '/answers/:id/new' => 'answers#new', as: :new_answer
      get '/answers/:id/friend_comments' => 'answers#friend_comments'
      get '/answers/:id/general_comments' => 'answers#general_comments'
      get '/answers/:id/likes' => 'answers#likes'

      # Post
      resources :posts, except: [:new]
      get '/posts/:id/friend_comments' => 'posts#friend_comments'
      get '/posts/:id/general_comments' => 'posts#general_comments'
      get '/posts/:id/likes' => 'posts#likes'

      # CustomQuestion
      resources :custom_questions, only: [:show, :create, :destroy, :update, :edit]
      post '/custom_questions/:id/repost' => 'custom_questions#repost_create', as: :custom_question_repost_form
      get '/custom_questions/:id/repost' => 'custom_questions#repost_new', as: :custom_question_repost
      get '/custom_questions/:id/friend_comments' => 'custom_questions#friend_comments'
      get '/custom_questions/:id/general_comments' => 'custom_questions#general_comments'
      get '/custom_questions/:id/likes' => 'custom_questions#likes'

      # Feed
      root 'feeds#friends'
      get '/feeds/general' => 'feeds#general', as: :general_feed

      # Question
      get '/questions/today' => 'questions#today', as: :today_questions
      get '/questions/:id/friends' => 'questions#show_friends', as: :question_friends
      get '/questions/:id/general' => 'questions#show_general', as: :question_general
      get '/questions/import_all' => 'questions#import_all', as: :import_all_questions
      get '/questions/import_new' => 'questions#import_new', as: :import_new_questions
      resources :questions, only: [:index, :show]

      # Comment
      resources :comments, only: [:create, :destroy]

      # Reply
      resources :replies, only: [:create, :destroy]

      # Like
      resources :likes, only: [:create, :destroy]
      get '/likes/:target_type/:target_id' => 'likes#likes_info'

      # Assignment
      get '/assignments' => 'assignments#index', as: :assignments

      get '/assignments/:question_id' => 'assignments#new', as: :new_assignment 
      post '/assignments/:assignee_id/:question_id' => 'assignments#create', as: :create_assignment # get?
      delete '/assignments/:assignee_id/:question_id' => 'assignments#destroy', as: :destroy_assignment
      
      post '/assignments/:assignee_id/custom_question/:custom_question_id' => 'assignments#create_custom', as: :create_custom_assignment # get?
      delete '/assignments/:assignee_id/custom_question/:custom_uestion_id' => 'assignments#destroy_custom', as: :destroy_custom_assignment
      get '/assignments/custom_question/:custom_question_id' => 'assignments#new_custom', as: :new_custom_assignment  

      # Drawer
      resources :drawers, only: [:create, :destroy]
      get '/drawers/:target_type/:target_id' => 'drawers#drawers_info'

      # Highlight
      resources :highlights, only: [:create, :destroy]

      # Notification
      get '/notifications/read_all' => 'notifications#read_all', as: :notification_read_all
      get '/notifications/:id' => 'notifications#read'
      get '/notifications/all/index' => 'notifications#index' , as: :notification_index 

      # Profile
      get '/profiles/:id' => 'profiles#index', as: :profile
      get '/profiles/:id/drawers' => 'profiles#drawers', as: :profile_drawers

      # User
      get '/users/:id/edit' => 'users#edit', as: :edit_user_profile
      patch '/users/:id/edit' => 'users#update', as: :update_user_profile
      # devise_for :users, :controllers => {:confirmations => 'users/confirmations', omniauth_callbacks: 'user/omniauth_callbacks' }
      devise_for :users, :controllers => {:confirmations => 'users/confirmations' }
      # 아래 코드는 이후에 멀티채널 구성에 맞추어 바뀌어야할수도.
      get '/users/friends' => 'users#friends', as: :friends
      put '/users/:id/image_upload' => 'users#image_upload', as: :image_upload
      # put '/users/:id/upload_image' => 'users#update', as: :upload_image
      post '/users/:id/add_friend' => 'users#add_friend', as: :add_friend # get?
      post '/users/:id/friend_request' => 'users#friend_request', as: :friend_request # get?
      

      # Invitation
      get '/invitations' => 'invitations#index', as: :invitation
      get '/invitations/link' => 'invitations#link', as: :invitation_link
      get '/invitations/:id(/:question_id1(/:question_id2(/:question_id3)))' => 'invitations#accept', as: :invitation_accept

      # Search
      get '/search/all' => 'search#all', as: :search_all
      get '/search/admin_question' => 'search#admin_question', as: :search_admin_question
      get '/search/custom_question' => 'search#custom_question', as: :search_custom_question
      get '/search/user' => 'search#user', as: :search_user

      # Channel
      resources :channels, only: [:create, :update, :destroy]
      put '/channels/:id/edit_friendship' => 'channels#edit_friendship'

      # Announcement
      resources :announcements, only: [:create, :update, :destroy]
      get '/announcements' => 'announcements#index', as: :announcement_index
      get '/announcements/admin'  => 'announcements#admin_index', as: :announcement_admin_index
      get '/announcements/:id/publish' => 'announcements#publish', as: :announcement_publish
      get '/announcements/:id/noti' => 'announcements#noti', as: :announcement_noti

app/models/announcement.rb
class Announcement < ApplicationRecord
    has_many   :comments, dependent: :destroy, as: :target

    scope :unpublished, -> { where(published_at: nil) }
    scope :published, -> { where.not(published_at: nil) }

    after_destroy :destroy_notifications

    def destroy_notifications
        Notification.where(target: self).destroy_all
    end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin, except: [:index]
  before_action :set_announcement, only: %i[publish unpublish noti destroy]

  def index
    @published_announcements = Announcement.published.sort_by(&:published_at).reverse!
    render 'index'
  end

  def admin_index
    @published_announcements = Announcement.published.sort_by(&:published_at).reverse!
    @unpublished_announcements = Announcement.unpublished.sort_by(&:created_at).reverse!

    render 'admin_index'
  end

  def create
    Announcement.create(content: params[:content], title: params[:title])
    redirect_to announcement_admin_index_path
  end

  def publish
    if @announcement.published_at.nil?
      @announcement.published_at = DateTime.now
      @announcement.save(touch: false) # updated_at을 update하지 않기 위해!!
    end

    User.all.each do |u|
      Notification.create(recipient: u, actor: User.find(1), target: @announcement, origin: @announcement, action: 'announcement')
    end

    redirect_to announcement_admin_index_path
  end

  def noti
    User.all.each do |u|
      Notification.create(recipient: u, actor: User.find(1), target: @announcement, origin: @announcement, action: 're_announcement')
    end
    redirect_to announcement_admin_index_path
  end

  def destroy
    @announcement.destroy

    redirect_to announcement_admin_index_path
  end

  private

  def check_admin
    redirect_to root_url unless current_user.has_role? :admin
  end

  def set_announcement
    @announcement = Announcement.find(params[:id])
  end
end

app/controllers/api/v1/announcements_controller.rb
class Api::V1::AnnouncementsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin, except: [:index]
  before_action :set_announcement, only: %i[publish unpublish noti destroy]

  def index
    @published_announcements = Announcement.published.sort_by(&:published_at).reverse!

    # render :index, locals: { published_announcements: @published_announcements }
  end

  def admin_index
    @published_announcements = Announcement.published.sort_by(&:published_at).reverse!
    @unpublished_announcements = Announcement.unpublished.sort_by(&:created_at).reverse!
  end

  def create
    if @announcement = Announcement.create(content: params[:content], title: params[:title])
      render json: {status: 'SUCCESS', message:'Created announcement', data: @announcement}, status: :ok
    else
      render json: {status: 'ERROR', message:'Announcement not created', data: @announcement.errors.full_messages}, status: :unprocessable_entity
    end
    # redirect_to api_v1_announcement_admin_index_path
  end

  def publish
    if @announcement.published_at.nil?
      @announcement.published_at = DateTime.now
      @announcement.save(touch: false) # updated_at을 update하지 않기 위해!!
    end

    User.all.each do |u|
      Notification.create(recipient: u, actor: User.find(1), target: @announcement, origin: @announcement, action: 'announcement')
    end

    # render :publish, locals: { announcement: @announcement }
    # redirect_to api_v1_announcement_admin_index_path
  end

  def noti
    User.all.each do |u|
      Notification.create(recipient: u, actor: User.find(1), target: @announcement, origin: @announcement, action: 're_announcement')
    end

    # redirect_to api_v1_announcement_admin_index_path
  end

  def destroy
    if @announcement.destroy
      render json: {status: 'SUCCESS', message:'Deleted announcement'},status: :ok
    else
      render json: {status: 'ERROR', message:'Announcement not deleted', data: @announcement.errors.full_messages}, status: :unprocessable_entity
    end

    # redirect_to api_v1_announcement_admin_index_path
  end

  private

  # def authenticate_user
  #   user_token = request.headers['X-USER-TOKEN']
  #   if user_token
  #     @user = User.find_by_token(user_token)
  #     #Unauthorize if a user object is not returned
  #     if @user.nil?
  #       return unauthorize
  #     end
  #   else
  #     return unauthorize
  #   end
  # end

  # def unauthorize
  #   head status: :unauthorized
  #   return false
  # end

  def check_admin
    # redirect_to root_url unless current_user.has_role? :admin
    if !current_user.has_role? :admin
      render json: {status: 'ERROR', message:'user not admin', data: current_user}, status: :unauthorized
    end
  end

  def set_announcement
    @announcement = Announcement.find(params[:id])
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/api/v1/announcements_helper.rb
module Api::V1::AnnouncementsHelper
end

app/views/announcements/admin_index.html.erb
<div class="inner-container">
    <%= link_to "일별 통계", daily_stats_path %><br>
    <%= link_to "월별 통계", monthly_stats_path %><br><br>

    <%= link_to "공지 페이지로", announcement_index_path %>
    <div class="prism-box-new-post">
        <div class="prism-box__content">
            <%= form_tag(announcements_path) do %>
                <%= text_field_tag :title, nil, required: true, placeholder: "제목", "data-enable-grammarly": "false", autocomplete: "off" %>
                <%= text_area_tag :content, nil, required: true, class: "new-answer-field",  placeholder: "공지 쓰기", "data-enable-grammarly": "false" %>
                <%= button_tag "저장", class: "answer-button"%>
            <% end %>
        </div>
    </div> 
    현재 발행중인 공지<br>
    <% @published_announcements.each do |a| %>
        <div class="prism-box">
            <div class="prism-box__header">
                <%= link_to '삭제', announcement_path(a.id), method: :delete%> | 
                <%= link_to '노티 한 번 더 보내기', announcement_noti_path(a.id) %>
            </div>
            <div class="prism-box__content">
                <div class="announcement-title"><%= a.title %></div>
                <div class="answer autolink"><p><%= auto_link(a.content) %></p></div><br><br>
                <div class = "date time">작성: <%= time_tag a.created_at %></div>
                <div class = "date time">발행: <%= time_tag a.published_at %></div>                </div><br><br>
            <% unread_users = [] %>
            <% n = (Notification.where(target: a, action: 'announcement').count) %>
            <% Notification.where(target: a, action: 'announcement').unread.each do |n| %>
                <% unread_users.push(n.recipient_id) %>
            <% end %>
            <p>첫 공지 도달률</P>
            <div>도달한 사용자: <%= User.all.ids - unread_users %></div>
            <div>도달률: <%= ((n-unread_users.count)*100.0/n).round(1) %>% (<%= n-unread_users.count %>명)</div>
            <% if !Notification.where(target: a, action: 're_announcement').empty? %>
                <%= rn = (Notification.where(target: a, action: 're_announcement').count) %>
                <% unread_users2 = [] %>
                <% Notification.where(target: a, action: 're_announcement').unread.each do |n| %>
                    <% unread_users2.push(n.recipient_id) %>
                <% end %>
                <p>두 번째 공지 도달률</p> (세번째 공지를 보낸 순간부터 이거는 의미없는 숫자입니다)
                <div>도달한 사용자: <%= User.all.ids - unread_users2 %></div>
                <div>도달률: <%= ((rn-unread_users2.count)*100.0/rn).round(1) %>% (<%= rn-unread_users2.count %>명)</div>
            <% end %>
        </div> 
    <% end %> 
    발행 안된 공지<br>
    <% @unpublished_announcements.each do |a| %>
        <div class="prism-box">
            <div class="prism-box__header">
                <% if a.published_at == nil %> 
                    <%= link_to "공지 발행하기", announcement_publish_path(a.id) %>
                <% end %>
                <%= link_to '삭제', announcement_path(a.id), method: :delete%>
            </div>
            <div class="prism-box__content">
                <div class="announcement-title"><%= a.title %></div>
                <div class="answer autolink"><p><%= auto_link(a.content) %></p></div><br><br>
                <div class = "date time">작성: <%= time_tag a.created_at %></div>
            </div><br><br>
        </div>
    <% end %> 
</div>

<script>
    $('body').trigger('click'); 
</script>

app/views/announcements/index.html.erb
<div class="inner-container">
    <% if user_signed_in? && (current_user.has_role? :admin) %>
        <%= link_to '공지 관리', announcement_admin_index_path %>
    <% end %>

    <% @published_announcements.each do |a| %>
        <div class="prism-box">
            <div class="prism-box__content"><br>
                <div class="announcement-title"><%= a.title %></div>
                <div class="answer autolink"><p><%= auto_link(a.content) %></p></div><br><br>
                <div class = "date time"><%= time_tag a.published_at %></div>
            </div>
            <%= render 'comments/general_form', user: current_user, feed: a %>
        </div>
    <% end %> 
</div>

<script> 
    $('body').trigger('click'); 
</script>