config/routes.rb
Rails.application.routes.draw do
  get 'register/info'

  get 'visitor/main'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Application
  get '/unread' => 'application#unread'
  get '/introduction' => 'application#intro', as: :introduction
  get '/require_confirmation' => 'application#require_confirmation', as: :require_confirmation

  # Answer
  resources :answers, except: [:new]
  get '/answers/:id/new' => 'answers#new', as: :new_answer

  # Post
  resources :posts, except: [:new]

  # CustomQuestion
  resources :custom_questions, only: [:show, :create, :destroy, :update, :edit]
  post '/custom_questions/:id/repost' => 'custom_questions#repost_create', as: :custom_question_repost
  get '/custom_questions/:id/repost' => 'custom_questions#repost_new', as: :custom_question_repost_new
  # get '/custom_questions/:id/repost/edit' => 'custom_questions#repost_edit', as: :custom_question_repost_edit

  # Feed
  root 'feeds#friends'
  get '/feeds/general' => 'feeds#general', as: :general_feed

  # Question 
  get '/questions/today' => 'questions#today', as: :today_questions
  get '/questions/:id/friends' => 'questions#show_friends', as: :question_friends
  get '/questions/:id/general' => 'questions#show_general', as: :question_general
  get '/questions/import_all' => 'questions#import_all', as: :import_all_questions
  get '/questions/import_new' => 'questions#import_new', as: :import_new_questions
  resources :questions, only: [:index, :show]

  # Comment
  resources :comments, only: [:create, :destroy] 

  # Reply
  resources :replies, only: [:create, :destroy]

  # Like
  resources :likes, only: [:create, :destroy]
  get '/likes/:target_type/:target_id' => 'likes#likes_info'

  # Assignment
  get '/assignments' => 'assignments#index', as: :assignments
  get '/assignments/:question_id' => 'assignments#new', as: :new_assignment
  post '/assignments/:assignee_id/:question_id' => 'assignments#create', as: :create_assignment # get?
  delete '/assignments/:assignee_id/:question_id' => 'assignments#destroy', as: :destroy_assignment
  post '/assignments/:assignee_id/custom_question/:custom_question_id' => 'assignments#create_custom', as: :create_custom_assignment # get?
  delete '/assignments/:assignee_id/custom_question/:custom_uestion_id' => 'assignments#destroy_custom', as: :destroy_custom_assignment
  get '/assignments/custom_question/:custom_question_id' => 'assignments#new_custom', as: :new_custom_assignment

  # Drawer
  resources :drawers, only: [:create, :destroy]
  get '/drawers/:target_type/:target_id' => 'drawers#drawers_info'

  # Highlight
  resources :highlights, only: [:create, :destroy]

  # Notification
  get '/notifications' => 'notifications#index' , as: :notifications
  get '/notifications/read_all' => 'notifications#read_all', as: :notification_read_all
  get '/notifications/:id' => 'notifications#read'

  # Profile
  get '/profiles/:id' => 'profiles#index', as: :profile
  get '/profiles/:id/drawers' => 'profiles#drawers', as: :profile_drawers

  # User
  get '/users/:id/edit' => 'users#edit', as: :edit_user_profile
  patch '/users/:id/edit' => 'users#update', as: :update_user_profile
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', :confirmations => 'users/confirmations', :passwords => 'users/passwords', :sessions => 'users/sessions' }
  # 아래 코드는 이후에 멀티채널 구성에 맞추어 바뀌어야할수도.
  get '/users/friends' => 'users#friends', as: :friends
  put '/users/:id/image_upload' => 'users#image_upload', as: :image_upload
  # put '/users/:id/upload_image' => 'users#update', as: :upload_image
  post '/users/:id/add_friend' => 'users#add_friend', as: :add_friend # get?
  post '/users/:id/delete_friend' => 'users#delete_friend', as: :delete_friend
  # post '/users/:id/friend_request' => 'users#friend_request', as: :friend_request_send # get?
  
  # FriendRequest
  resources :friend_requests, only: [:destroy]
  get '/friend_requests' => 'friend_requests#index', as: :friend_requests
  post '/friend_requests/:id' => 'friend_requests#create', as: :friend_request_create
  put '/friend_requests/:id/deny' => 'friend_requests#deny', as: :friend_request_deny

  # Invitation
  get '/invitations' => 'invitations#index', as: :invitations
  get '/invitations/link' => 'invitations#link', as: :invitation_link
  get '/invitations/:id(/:question_id1(/:question_id2(/:question_id3)))' => 'invitations#accept', as: :invitation_accept

  # Search
  get '/search/all' => 'search#all', as: :search_all
  get '/search/admin_question' => 'search#admin_question', as: :search_admin_question
  get '/search/custom_question' => 'search#custom_question', as: :search_custom_question
  get '/search/user' => 'search#user', as: :search_user

  # Channel
  resources :channels, only: [:create, :update, :destroy]
  put '/channels/:id/edit_friendship' => 'channels#edit_friendship'

  # Announcement
  resources :announcements, only: [:create, :update, :destroy]
  get '/announcements' => 'announcements#index', as: :announcement_index
  get '/announcements/admin'  => 'announcements#admin_index', as: :announcement_admin_index
  get '/announcements/:id/publish' => 'announcements#publish', as: :announcement_publish
  get '/announcements/:id/noti' => 'announcements#noti', as: :announcement_noti

  # User Stats
  get '/stats/daily' => 'stats#daily', as: :daily_stats
  get '/stats/monthly' => 'stats#monthly', as: :monthly_stats
  
  namespace 'api' do
    namespace 'v1', defaults: { format: :json } do
      
      # Sessions
      resource :sessions, only: [:create, :destroy, :show] # delete request가 실제로 user을 delete하는 것이 아니기 때문에 resources가 아니라 resource로 두는 것이 맞습니다. 고치지 말아주세요!
      resources :users, only: [:create] 

      # Answer
      resources :answers, except: [:new]
      get '/answers/:id/new' => 'answers#new', as: :new_answer
      get '/answers/:id/friend_comments' => 'answers#friend_comments'
      get '/answers/:id/general_comments' => 'answers#general_comments'
      get '/answers/:id/likes' => 'answers#likes'

      # Post
      resources :posts, except: [:new]
      get '/posts/:id/friend_comments' => 'posts#friend_comments'
      get '/posts/:id/general_comments' => 'posts#general_comments'
      get '/posts/:id/likes' => 'posts#likes'

      # CustomQuestion
      resources :custom_questions, only: [:show, :create, :destroy, :update, :edit]
      post '/custom_questions/:id/repost' => 'custom_questions#repost_create', as: :custom_question_repost_form
      get '/custom_questions/:id/repost' => 'custom_questions#repost_new', as: :custom_question_repost
      get '/custom_questions/:id/friend_comments' => 'custom_questions#friend_comments'
      get '/custom_questions/:id/general_comments' => 'custom_questions#general_comments'
      get '/custom_questions/:id/likes' => 'custom_questions#likes'

      # Feed
      root 'feeds#friends'
      get '/feeds/general' => 'feeds#general', as: :general_feed

      # Question
      get '/questions/today' => 'questions#today', as: :today_questions
      get '/questions/:id/friends' => 'questions#show_friends', as: :question_friends
      get '/questions/:id/general' => 'questions#show_general', as: :question_general
      get '/questions/import_all' => 'questions#import_all', as: :import_all_questions
      get '/questions/import_new' => 'questions#import_new', as: :import_new_questions
      resources :questions, only: [:index, :show]

      # Comment
      resources :comments, only: [:create, :destroy]

      # Reply
      resources :replies, only: [:create, :destroy]

      # Like
      resources :likes, only: [:create, :destroy]
      get '/likes/:target_type/:target_id' => 'likes#likes_info'

      # Assignment
      get '/assignments' => 'assignments#index', as: :assignments

      get '/assignments/:question_id' => 'assignments#new', as: :new_assignment 
      post '/assignments/:assignee_id/:question_id' => 'assignments#create', as: :create_assignment # get?
      delete '/assignments/:assignee_id/:question_id' => 'assignments#destroy', as: :destroy_assignment
      
      post '/assignments/:assignee_id/custom_question/:custom_question_id' => 'assignments#create_custom', as: :create_custom_assignment # get?
      delete '/assignments/:assignee_id/custom_question/:custom_uestion_id' => 'assignments#destroy_custom', as: :destroy_custom_assignment
      get '/assignments/custom_question/:custom_question_id' => 'assignments#new_custom', as: :new_custom_assignment  

      # Drawer
      resources :drawers, only: [:create, :destroy]
      get '/drawers/:target_type/:target_id' => 'drawers#drawers_info'

      # Highlight
      resources :highlights, only: [:create, :destroy]

      # Notification
      get '/notifications/read_all' => 'notifications#read_all', as: :notification_read_all
      get '/notifications/:id' => 'notifications#read'
      get '/notifications/all/index' => 'notifications#index' , as: :notification_index 

      # Profile
      get '/profiles/:id' => 'profiles#index', as: :profile
      get '/profiles/:id/drawers' => 'profiles#drawers', as: :profile_drawers

      # User
      get '/users/:id/edit' => 'users#edit', as: :edit_user_profile
      patch '/users/:id/edit' => 'users#update', as: :update_user_profile
      # devise_for :users, :controllers => {:confirmations => 'users/confirmations', omniauth_callbacks: 'user/omniauth_callbacks' }
      devise_for :users, :controllers => {:confirmations => 'users/confirmations' }
      # 아래 코드는 이후에 멀티채널 구성에 맞추어 바뀌어야할수도.
      get '/users/friends' => 'users#friends', as: :friends
      put '/users/:id/image_upload' => 'users#image_upload', as: :image_upload
      # put '/users/:id/upload_image' => 'users#update', as: :upload_image
      post '/users/:id/add_friend' => 'users#add_friend', as: :add_friend # get?
      post '/users/:id/friend_request' => 'users#friend_request', as: :friend_request # get?
      

      # Invitation

app/controllers/api/v1/feeds_controller.rb
class Api::V1::FeedsController < ApplicationController
  before_action :authenticate_user!

  respond_to :json

  def general
    @feeds = Answer.channel_name('익명피드').anonymous(current_user.id) + Post.channel_name('익명피드').anonymous(current_user.id) + CustomQuestion.channel_name('익명피드').anonymous(current_user.id)
    @feeds = @feeds.sort_by(&:created_at).reverse!

    # render :feeds, locals: { feeds: @feeds }
    @feeds = @feeds.paginate(:page => params[:page], :per_page => 7)
    render json: @feeds
  end

  def friends
    answers = Answer.accessible(current_user.id) + Answer.where(author: current_user)
    posts = Post.accessible(current_user.id) + Post.where(author: current_user)
    custom_questions = CustomQuestion.accessible(current_user.id) + CustomQuestion.where(author: current_user)
    @feeds = answers + posts + custom_questions
    @feeds = @feeds.sort_by(&:created_at).reverse!

    @feeds = @feeds.paginate(:page => params[:page], :per_page => 7)

    render json: @feeds, adapter: :json_api

    # render :feeds, locals: { feeds: @feeds }
  end

  # private 

  # def authenticate_user
  #   user_token = request.headers['X-USER-TOKEN']
  #   if user_token
  #     @user = User.find_by_token(user_token)
  #     #Unauthorize if a user object is not returned
  #     if @user.nil?
  #       return unauthorize
  #     end
  #   else
  #     return unauthorize
  #   end
  # end

  # def unauthorize
  #   head status: :unauthorized
  #   return false
  # end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_username
    
    def general
        @feeds = Answer.channel_name("익명피드").anonymous(current_user.id) + Post.channel_name("익명피드").anonymous(current_user.id) + CustomQuestion.channel_name("익명피드").anonymous(current_user.id)
        @feeds = @feeds.sort_by(&:created_at).reverse!

        @feeds = @feeds.paginate(:page => params[:page], :per_page => 7)
        
        render 'general'
    end
 
    def friends
        answers = Answer.accessible(current_user.id) + Answer.where(author: current_user)
        posts = Post.accessible(current_user.id) + Post.where(author:current_user)
        custom_questions = CustomQuestion.accessible(current_user.id) + CustomQuestion.where(author: current_user)
        @feeds = answers + posts + custom_questions
        @feeds = @feeds.sort_by(&:created_at).reverse!

        @feeds = @feeds.paginate(:page => params[:page], :per_page => 7)

        render 'friends'
    end

    private
    def check_username
        if current_user.username.nil?
            redirect_to edit_user_profile_path(current_user)
        end
    end
end
  

app/helpers/api/v1/feeds_helper.rb
module Api::V1::FeedsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_delete_or_edit.html.erb
<%= image_tag "icons/read-more-icon.png", class:"btn-read-more hover-pointer"%>
<span class = "edit-or-delete" style="display: none;">
    <% if feed.is_a? Answer %>
        <div class="edit-or-delete-el feed-edit answer-edit hover-pointer" data-url='<%=edit_answer_path(feed.id)%>'>수정</div>
        <div class="edit-or-delete-el btn-feed-delete hover-pointer" data-url="<%=answer_path(feed.id)%>">삭제</div>
    <% elsif feed.is_a? Post %>
        <div class="edit-or-delete-el feed-edit post-edit hover-pointer" data-url='<%=edit_post_path(feed.id)%>'>수정</div>
        <div class="edit-or-delete-el btn-feed-delete hover-pointer" data-url="<%=post_path(feed.id)%>">삭제</div>
    <% else %>
        <% if (feed.ancestor_id == nil) && (current_user.id == feed.author.id) %>
            <div class="edit-or-delete-el feed-edit hover-pointer" data-url="<%= edit_custom_question_path(feed.id) %>">공개그룹</div>
            <div class="edit-or-delete-el btn-feed-delete hover-pointer" data-url="<%=custom_question_path(feed.id)%>">삭제</div>
        <% else %>
            <div class="edit-or-delete-el feed-edit hover-pointer" data-url='<%=edit_custom_question_path(feed.id)%>'>수정</div>
            <div class="edit-or-delete-el btn-feed-delete hover-pointer" data-url="<%=custom_question_path(feed.id)%>">삭제</div>
        <% end %>
    <% end %>
</span>

app/views/feeds/_feed_footer.html.erb
<div class = "likes"> 
    <%= render 'likes/default', target: target, like_btn_class: "btn-feed-like" %>
</div>
<div class = "drawers">
    <%= render 'drawers/default', target: target %>
</div>

app/views/feeds/_friends_index.html.erb
<% if feeds.empty? %>
    <div id = "friend-box-invitation">
        <%= link_to "+ 친구 초대하기", invitations_path, class: "btn-invitation" %>
    </div>
<% else %>
    <% feeds.each do |feed| %>
        <!-- custom question feed -->
        <% if feed.is_a? CustomQuestion %>
            <div class="prism-box custom-feed <%=feed.id%>">
                <div class="prism-box__header">
                    <%= render partial: "./user_profile", locals: {user: feed.author} %>
                    <% if current_user.id == feed.author.id %>
                        <%= render 'feeds/delete_or_edit', feed: feed %>
                    <% end %>
                </div>
                <div class = "prism-box__content">
                    <div class = "prism-box-custom-question">
                        <div class = "question-content autolink"><p><%= auto_link(feed.content) %></p></div>
                        <div class="question-tags">
                            <% feed.tags.each do |tag| %>
                                <%= form_tag(search_custom_question_path, method: :get, class: "more") do %>
                                    <%= hidden_field_tag :query, tag.content %>
                                    <%= button_tag tag.content, class: "question-tag" %>
                                <% end %>
                            <% end %>
                        </div>
                        <div class = "reposts">
                            <%= render 'custom_questions/repost', custom_question: feed %>
                        </div>
                    </div>
                    <% if feed.ancestor_id != nil %>
                        <div class = "answer autolink">
                            <% if feed.repost_message? %>
                                <p><%= auto_link(feed.repost_message) %></p>
                            <% end %>
                        </div>
                        <br>
                    <% end %> 
                    <div class = "date time"><%= time_tag feed.created_at, class: "timeago" %></div>
                </div>
                <div class="prism-box__footer">
                    <% if current_user.id == feed.author.id %>
                        <%= render 'feeds/my_feed_footer', target: feed %>
                    <% else %>
                        <%= render 'feeds/feed_footer', target: feed %>
                    <% end %>
                </div>
                <%= render 'comments/friends_form', user: feed.author, feed: feed %>
            </div>

        <!-- posting or Answer -->
        <% else %>
            <% if feed.is_a? Answer %>
                <div class="prism-box answer-feed <%=feed.id%>">
            <% else %>
                <div class="prism-box post-feed <%=feed.id%>">
            <% end %>
                <div class="prism-box__header">
                    <%= render partial: "./user_profile", locals: {user: feed.author} %>
                    <% if current_user.id == feed.author.id %>
                        <%= render 'feeds/delete_or_edit', feed: feed %>
                    <% end %>
                </div>
                <div class = "prism-box__content">
                    <% if feed.is_a? Answer %>
                        <div class = "prism-box-question">
                            <%= link_to feed.question.content, question_path(feed.question.id), class: "question"%>
                        </div>
                    <% else %>
                        <br>
                    <% end %>
                    <div class="answer autolink"><%= auto_link(feed.content) %></div><br>
                    <div class = "date time"><%= time_tag feed.created_at, class: "timeago" %></div>
                </div>
                <div class="prism-box__footer">
                    <% if current_user.id == feed.author.id %>
                        <%= render 'feeds/my_feed_footer', target: feed %>
                    <% else %>
                        <%= render 'feeds/feed_footer', target: feed %>
                    <% end %>
                </div>
                <%= render 'comments/friends_form', user: feed.author, feed: feed %>
            </div>
        <% end %>   
    <% end %>
<% end %>

<%= will_paginate @feeds %>

app/views/feeds/_general_index.html.erb
<% feeds.each do |feed| %>
    <!-- custom question feed -->
    <% if feed.is_a? CustomQuestion %>
        <div class="prism-box custom-feed <%=feed.id%>">
            <div class="prism-box__header">
                <%= render partial: "./user_profile_general", locals: {user_id: feed.author.id, feed_id: feed.id} %>
            </div>
            <div class = "prism-box__content">
                <div class = "prism-box-custom-question">
                    <div class = "question-content autolink"><p><%= auto_link(feed.content) %></p></div>
                    <div class="question-tags">
                        <% feed.tags.each do |tag| %>
                            <%= form_tag(search_custom_question_path, method: :get, class: "more") do %>
                                <%= hidden_field_tag :query, tag.content %>
                                <%= button_tag tag.content, class: "question-tag" %>
                            <% end %>
                        <% end %>
                    </div>
                    <div class = "reposts">
                        <%= render 'custom_questions/repost', custom_question: feed %>
                    </div>
                </div>
                <% if feed.ancestor_id != nil %>
                    <div class = "repost-message autolink">
                        <% if feed.repost_message? %>
                            <p><%= auto_link(feed.repost_message) %></p>
                        <% end %>
                    </div>
                    <br>
                <% end %> 
                <div class = "date time"><%= time_tag feed.created_at, class: "timeago" %></div>
            </div>
            <div class="prism-box__footer">
                <%= render 'feeds/feed_footer', target: feed %>
            </div>
            <%= render 'comments/general_form', user: feed.author, feed: feed %>
        </div>

    <!-- posting or Answer -->
    <% else %>
        <% if feed.is_a? Answer %>
            <div class="prism-box answer-feed <%=feed.id%>">
        <% else %>
            <div class="prism-box post-feed <%=feed.id%>">
        <% end %>
            <div class="prism-box__header">
                <%= render partial: "./user_profile_general", locals: {user_id: feed.author.id, feed_id: feed.id}%>
            </div>
            <div class = "prism-box__content">
                <% if feed.is_a? Answer %>
                    <div class = "prism-box-question">
                        <%= link_to feed.question.content, question_path(feed.question.id), class: "question"%>
                    </div>
                <% else %>
                    <br>
                <% end %>
                <div class="answer autolink"><%= auto_link(feed.content) %></div><br>
                <div class = "date time"><%= time_tag feed.created_at, class: "timeago" %></div>
            </div>
            <div class="prism-box__footer">
                <%= render 'feeds/feed_footer', target: feed %>
            </div>
            <%= render 'comments/general_form', user: feed.author, feed: feed %>
        </div>
    <% end %>   
<% end %>

<%= will_paginate @feeds %>

app/views/feeds/_my_feed_footer.html.erb
<div class = "likes"> 
    <%= render 'likes/num_of_likes', target: target %>
    <%= render 'likes/default', target: target, like_btn_class: "btn-feed-like" %>
</div>
<div class = "drawers">
    <%= render 'drawers/num_of_drawers', target: target %>
    <%= render 'drawers/default', target: target %>
</div>
<div class="feed-channels"> <strong style = "padding-right: 10px; color: #4f4f4f;">공개그룹</strong>
    <% target.channels.each do |c| %>
        <% if c.id != target.channels.last.id %>
            <%= c.name %> |
        <% else %>
            <%= c.name %> 
        <% end %>
    <% end %>
</div>

<script>
    $('body').trigger('click');
</script>

app/views/feeds/friends.html.erb
<br/>
<div class="inner-container">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">포스트</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">질문</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <%= render 'posts/new'%>
    </div>
    <div class="tab-pane" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <%= render partial: "custom_questions/new", locals: {custom_question: CustomQuestion.new} %>
    </div> 
  </div>
  <div id='infinite-feeds'>
    <%= render partial: 'feeds/friends_index', locals: {feeds: @feeds} %>
  </div>
</div> 

<script>
  $('body').trigger('click');
  check_channels($(".answer-button"))

  // $(".posting").on('click', function () {
  //   var selected = $(this);
  //   $(this).addClass("selected");
  //   $('.custom-question').removeClass("selected");
  //   $(this).parent().parent().parent().removeClass("custom-question-form");
  //   $(this).parent().parent().removeClass("custom-question-form");
  //   $('#new-post-form').show();
  //   $('#new-custom-question-form').hide();
  // })

  // $(".custom-question").on('click', function () {
  //   var selected = $(this);
  //   $(this).addClass("selected");
  //   $(this).parent().parent().parent().addClass("custom-question-form");
  //   $(this).parent().parent().addClass("custom-question-form");
  //   $('.posting').removeClass("selected");
  //   $('#new-custom-question-form').show();
  //   $('#new-post-form').hide();
  // })
</script>
<script>

  $("#tags input").on({
    focusout : function() {
      var txt = this.value.replace(/[\<\>\,\r\n\;\\]/ig,''); // allowed characters
      // console.log(txt)
      if(txt.trim()!=''){
        let tag = $("<span/>", {text:txt.trim(), insertBefore:this, addClass:'tag'});
        tag.append(`<img src="/assets/icons/close-default-icon.png" alt="Exit Icon" class="tag-close">`)
        
        tag.find(".tag-close").on('click', function() {
          tag.remove(); 
        });
      }

      this.value = "";
    },
    keyup : function(e) {
      // if: comma|enter (delimit more keyCodes with | pipe)
      if(/(188|13)/.test(e.which)) $(this).focusout(); 
    }
  });

  $(".new_custom_question").submit(function(e) {
    e.preventDefault();
    form = $(this)

    var tag_string = ""
    $("#tags").find(".tag").each(function() {
      tag_string += $(this).text() + '\r\n'
    })

    form.find("#custom_question_tag_string").val(tag_string)

    $.ajax({
        type: "POST",
        url: form.attr('action'),
        data: form.serialize(),
        success: function(data) {
            console.log("successed!")
        },
        error: function(data) {
            console.log("error!")
        }
    })
  })
</script>

app/views/feeds/friends.js.erb
$('#infinite-feeds').append('<%= escape_javascript render partial: 'feeds/friends_index', locals: {feeds: @feeds} %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@feeds) %>');
$('body').trigger('click');

app/views/feeds/general.html.erb
<div class="inner-container">
  <% if @feeds.count() > 0 %>
    <div id='infinite-feeds'>
      <%= render partial: 'feeds/general_index', locals: {feeds: @feeds} %>

    </div>
  <% else %>
    <div>아직 공유된 게시물이 없습니다.</div>
  <% end %>
</div> 
<!--더보기는 지금 구현하는 건 아닌 듯-->

<script>
  $('body').trigger('click');
</script> 

app/views/feeds/general.js.erb
$('#infinite-feeds').append('<%= escape_javascript render partial: 'feeds/general_index', locals: {feeds: @feeds} %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@feeds) %>');
$('body').trigger('click'); 