config/routes.rb
Rails.application.routes.draw do
  get 'register/info'

  get 'visitor/main'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Application
  get '/unread' => 'application#unread'
  get '/introduction' => 'application#intro', as: :introduction
  get '/require_confirmation' => 'application#require_confirmation', as: :require_confirmation

  # Answer
  resources :answers, except: [:new]
  get '/answers/:id/new' => 'answers#new', as: :new_answer

  # Post
  resources :posts, except: [:new]

  # CustomQuestion
  resources :custom_questions, only: [:show, :create, :destroy, :update, :edit]
  post '/custom_questions/:id/repost' => 'custom_questions#repost_create', as: :custom_question_repost
  get '/custom_questions/:id/repost' => 'custom_questions#repost_new', as: :custom_question_repost_new
  # get '/custom_questions/:id/repost/edit' => 'custom_questions#repost_edit', as: :custom_question_repost_edit

  # Feed
  root 'feeds#friends'
  get '/feeds/general' => 'feeds#general', as: :general_feed

  # Question 
  get '/questions/today' => 'questions#today', as: :today_questions
  get '/questions/:id/friends' => 'questions#show_friends', as: :question_friends
  get '/questions/:id/general' => 'questions#show_general', as: :question_general
  get '/questions/import_all' => 'questions#import_all', as: :import_all_questions
  get '/questions/import_new' => 'questions#import_new', as: :import_new_questions
  resources :questions, only: [:index, :show]

  # Comment
  resources :comments, only: [:create, :destroy] 

  # Reply
  resources :replies, only: [:create, :destroy]

  # Like
  resources :likes, only: [:create, :destroy]
  get '/likes/:target_type/:target_id' => 'likes#likes_info'

  # Assignment
  get '/assignments' => 'assignments#index', as: :assignments
  get '/assignments/:question_id' => 'assignments#new', as: :new_assignment
  post '/assignments/:assignee_id/:question_id' => 'assignments#create', as: :create_assignment # get?
  delete '/assignments/:assignee_id/:question_id' => 'assignments#destroy', as: :destroy_assignment
  post '/assignments/:assignee_id/custom_question/:custom_question_id' => 'assignments#create_custom', as: :create_custom_assignment # get?
  delete '/assignments/:assignee_id/custom_question/:custom_uestion_id' => 'assignments#destroy_custom', as: :destroy_custom_assignment
  get '/assignments/custom_question/:custom_question_id' => 'assignments#new_custom', as: :new_custom_assignment

  # Drawer
  resources :drawers, only: [:create, :destroy]
  get '/drawers/:target_type/:target_id' => 'drawers#drawers_info'

  # Highlight
  resources :highlights, only: [:create, :destroy]

  # Notification
  get '/notifications' => 'notifications#index' , as: :notifications
  get '/notifications/read_all' => 'notifications#read_all', as: :notification_read_all
  get '/notifications/:id' => 'notifications#read'

  # Profile
  get '/profiles/:id' => 'profiles#index', as: :profile
  get '/profiles/:id/drawers' => 'profiles#drawers', as: :profile_drawers

  # User
  get '/users/:id/edit' => 'users#edit', as: :edit_user_profile
  patch '/users/:id/edit' => 'users#update', as: :update_user_profile
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', :confirmations => 'users/confirmations', :passwords => 'users/passwords', :sessions => 'users/sessions' }
  # 아래 코드는 이후에 멀티채널 구성에 맞추어 바뀌어야할수도.
  get '/users/friends' => 'users#friends', as: :friends
  put '/users/:id/image_upload' => 'users#image_upload', as: :image_upload
  # put '/users/:id/upload_image' => 'users#update', as: :upload_image
  post '/users/:id/add_friend' => 'users#add_friend', as: :add_friend # get?
  post '/users/:id/delete_friend' => 'users#delete_friend', as: :delete_friend
  # post '/users/:id/friend_request' => 'users#friend_request', as: :friend_request_send # get?
  
  # FriendRequest
  resources :friend_requests, only: [:destroy]
  get '/friend_requests' => 'friend_requests#index', as: :friend_requests
  post '/friend_requests/:id' => 'friend_requests#create', as: :friend_request_create
  put '/friend_requests/:id/deny' => 'friend_requests#deny', as: :friend_request_deny

  # Invitation
  get '/invitations' => 'invitations#index', as: :invitations
  get '/invitations/link' => 'invitations#link', as: :invitation_link
  get '/invitations/:id(/:question_id1(/:question_id2(/:question_id3)))' => 'invitations#accept', as: :invitation_accept

  # Search
  get '/search/all' => 'search#all', as: :search_all
  get '/search/admin_question' => 'search#admin_question', as: :search_admin_question
  get '/search/custom_question' => 'search#custom_question', as: :search_custom_question
  get '/search/user' => 'search#user', as: :search_user

  # Channel
  resources :channels, only: [:create, :update, :destroy]
  put '/channels/:id/edit_friendship' => 'channels#edit_friendship'

  # Announcement
  resources :announcements, only: [:create, :update, :destroy]
  get '/announcements' => 'announcements#index', as: :announcement_index
  get '/announcements/admin'  => 'announcements#admin_index', as: :announcement_admin_index
  get '/announcements/:id/publish' => 'announcements#publish', as: :announcement_publish
  get '/announcements/:id/noti' => 'announcements#noti', as: :announcement_noti

  # User Stats
  get '/stats/daily' => 'stats#daily', as: :daily_stats
  get '/stats/monthly' => 'stats#monthly', as: :monthly_stats
  
  namespace 'api' do
    namespace 'v1', defaults: { format: :json } do
      
      # Sessions
      resource :sessions, only: [:create, :destroy, :show] # delete request가 실제로 user을 delete하는 것이 아니기 때문에 resources가 아니라 resource로 두는 것이 맞습니다. 고치지 말아주세요!
      resources :users, only: [:create] 

      # Answer
      resources :answers, except: [:new]
      get '/answers/:id/new' => 'answers#new', as: :new_answer
      get '/answers/:id/friend_comments' => 'answers#friend_comments'
      get '/answers/:id/general_comments' => 'answers#general_comments'
      get '/answers/:id/likes' => 'answers#likes'

      # Post
      resources :posts, except: [:new]
      get '/posts/:id/friend_comments' => 'posts#friend_comments'
      get '/posts/:id/general_comments' => 'posts#general_comments'
      get '/posts/:id/likes' => 'posts#likes'

      # CustomQuestion
      resources :custom_questions, only: [:show, :create, :destroy, :update, :edit]
      post '/custom_questions/:id/repost' => 'custom_questions#repost_create', as: :custom_question_repost_form
      get '/custom_questions/:id/repost' => 'custom_questions#repost_new', as: :custom_question_repost
      get '/custom_questions/:id/friend_comments' => 'custom_questions#friend_comments'
      get '/custom_questions/:id/general_comments' => 'custom_questions#general_comments'
      get '/custom_questions/:id/likes' => 'custom_questions#likes'

      # Feed
      root 'feeds#friends'
      get '/feeds/general' => 'feeds#general', as: :general_feed

      # Question
      get '/questions/today' => 'questions#today', as: :today_questions
      get '/questions/:id/friends' => 'questions#show_friends', as: :question_friends
      get '/questions/:id/general' => 'questions#show_general', as: :question_general
      get '/questions/import_all' => 'questions#import_all', as: :import_all_questions
      get '/questions/import_new' => 'questions#import_new', as: :import_new_questions
      resources :questions, only: [:index, :show]

      # Comment
      resources :comments, only: [:create, :destroy]

      # Reply
      resources :replies, only: [:create, :destroy]

      # Like
      resources :likes, only: [:create, :destroy]
      get '/likes/:target_type/:target_id' => 'likes#likes_info'

      # Assignment
      get '/assignments' => 'assignments#index', as: :assignments

      get '/assignments/:question_id' => 'assignments#new', as: :new_assignment 
      post '/assignments/:assignee_id/:question_id' => 'assignments#create', as: :create_assignment # get?
      delete '/assignments/:assignee_id/:question_id' => 'assignments#destroy', as: :destroy_assignment
      
      post '/assignments/:assignee_id/custom_question/:custom_question_id' => 'assignments#create_custom', as: :create_custom_assignment # get?
      delete '/assignments/:assignee_id/custom_question/:custom_uestion_id' => 'assignments#destroy_custom', as: :destroy_custom_assignment
      get '/assignments/custom_question/:custom_question_id' => 'assignments#new_custom', as: :new_custom_assignment  

      # Drawer
      resources :drawers, only: [:create, :destroy]
      get '/drawers/:target_type/:target_id' => 'drawers#drawers_info'

      # Highlight
      resources :highlights, only: [:create, :destroy]

      # Notification
      get '/notifications/read_all' => 'notifications#read_all', as: :notification_read_all
      get '/notifications/:id' => 'notifications#read'
      get '/notifications/all/index' => 'notifications#index' , as: :notification_index 

      # Profile
      get '/profiles/:id' => 'profiles#index', as: :profile
      get '/profiles/:id/drawers' => 'profiles#drawers', as: :profile_drawers

      # User
      get '/users/:id/edit' => 'users#edit', as: :edit_user_profile
      patch '/users/:id/edit' => 'users#update', as: :update_user_profile
      # devise_for :users, :controllers => {:confirmations => 'users/confirmations', omniauth_callbacks: 'user/omniauth_callbacks' }
      devise_for :users, :controllers => {:confirmations => 'users/confirmations' }
      # 아래 코드는 이후에 멀티채널 구성에 맞추어 바뀌어야할수도.
      get '/users/friends' => 'users#friends', as: :friends
      put '/users/:id/image_upload' => 'users#image_upload', as: :image_upload
      # put '/users/:id/upload_image' => 'users#update', as: :upload_image
      post '/users/:id/add_friend' => 'users#add_friend', as: :add_friend # get?
      post '/users/:id/friend_request' => 'users#friend_request', as: :friend_request # get?
      

      # Invitation

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :actor, class_name: 'User'
  belongs_to :target, polymorphic: true  
  belongs_to :origin, polymorphic: true
  # target can be answer, friendrequest, friendship, assignment, highlight or comment 
  # polymorphic type이기 때문에 target만 보내주면 target_id와 target_type이 알아서 생성됨.
  # https://guides.rubyonrails.org/association_basics.html#polymorphic-associations 참조


  # 예외까지 포괄하는 결론: origin은 noti의 target의 target이고, noti의 target의 target이 없는 경우 노티의 발생지이다.
  # origin은 noti를 눌렀을 때 이동하는 페이지에 대응하는 모델 (노티의 발생지)
  # 예: 그 노티를 눌렀을 때 answer_path(:id)로 가야하면 그 id를 가진 answer이 origin임!
  # noti의 target이 answer, highlight, drawer, comment인 경우 answer이고
  # noti의 target이 friendship, friendrequest인 경우 noti의 actor인 user이고
  # noti의 target이 assignment인 경우 해당 assignment의 question / custom_question이다
  # noti의 target이 announcement인 경우 announcement자체이다
  # noti의 target이 custom question인 경우 그 custom question의 ancestor인 custom question이다
  ##### 예외: noti의 target이 reply의 origin은 그 reply가 달린 댓글이다.
  ##### 예외2: noti의 target이 like인 경우 origin은 그 like의 target이다

  # notification.unread로 확인하지 않은 노티들을 찾을 수 있음
  scope :unread, -> { where(read_at: nil) }
  scope :invisible, -> {where(invisible: true)}
  scope :visible, -> {where(invisible: false)}
  
end

app/controllers/api/v1/notifications_controller.rb
class Api::V1::NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = Notification.all

    render :index, { notifications: @notifications }
  end

  def read_all
    Notification.where(recipient_id: current_user.id).unread.each do |n|
      n.read_at = DateTime.now
      n.save(touch: false)
    end
    # redirect_back(fallback_location: root_path)
    # redirect_to request.referrer
  end

  def read
    noti = Notification.find(params[:id])

    if noti.recipient_id != current_user.id
      render json: {status: 'ERROR', message:'not accessible', data: current_user}, status: :unauthorized
    else
      if noti.read_at.nil?
        noti.read_at = DateTime.now
        noti.save(touch: false) # updated_at을 update하지 않기 위해!!
      end

      render :noti, { notification: noti }
    end
  end

  # private

  # def authenticate_user
  #   user_token = request.headers['X-USER-TOKEN']
  #   if user_token
  #     @user = User.find_by_token(user_token)
  #     #Unauthorize if a user object is not returned
  #     if @user.nil?
  #       return unauthorize
  #     end
  #   else
  #     return unauthorize
  #   end
  # end

  # def unauthorize
  #   head status: :unauthorized
  #   return false
  # end
end

app/helpers/api/v1/notifications_helper.rb
module Api::V1::NotificationsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_header.html.erb
<div class="prism-title" style = "margin-bottom: 20px"><h1>알림 모아보기</h1></div>
<div>
    <%= active_link_to '전체', notifications_path, class: "noti-link", active: :exclusive %>&nbsp; |&nbsp; 
    <%= active_link_to '친구 요청', friend_requests_path, class: "noti-link" %>&nbsp; |&nbsp; 
    <%= active_link_to '받은 질문', assignments_path, class: "noti-link", active: :exclusive %><br><br>
</div>

app/views/notifications/_list.html.erb
<% notifications.each do |noti| %>
    <% user = User.find(noti.actor_id)%>
    <% username = user.username %>

            <% if from == "layout" %>
        <% if noti.read_at != nil %>
    <div class="noti-el" data-url="/notifications/<%=noti.id%>">
        <% else %>
    <div class="noti-el unread" data-url="/notifications/<%=noti.id%>">
        <% end %>
            <% elsif from == "index" %>
        <% if noti.read_at != nil %>
    <div class="noti-box" data-url="/notifications/<%=noti.id%>">
        <% else %>
    <div class="noti-box unread" data-url="/notifications/<%=noti.id%>">
        <% end %>
            <% end %>

        <div class="noti-image">
            <% if noti.target_type == 'Drawer' || noti.target_type == 'CustomQuestion' || (noti.action? && noti.action.start_with?("anonymous")) %>
                <%# color = user.id + noti.target.id %>
                <%# r = color * color *color % 256 %>
                <%# g = (r * color) % 256 %>
                <%# b = (g * color) % 256 %>
                <button class="noti-image-anonymous" style="background-color: #072e75; "></button>
            <% else %>
                <%= image_tag user.image.url, class: "noti-image-named" %>
            <% end %>
        </div>

            <% if from == "layout" %>
        <div class="noti-text">
            <% elsif from == "index" %>
        <div class="noti-box-text">
            <% end %>

            <% case noti.target_type%>
            <% when 'Like' %>
                <% message = "\"" + noti.origin.content.truncate(30, separator: /\s/) + "\"" %>
                <% if noti.origin.likes.size == 1 %>
                    <% case noti.action %>
                    <% when 'friend_like_article' %>
                        <p><strong><%=username%></strong>님이 당신의 글을 좋아했습니다: <%= message %></p>
                    <% when 'friend_like_comment' %>
                        <p><strong><%=username%></strong>님이 당신의 댓글을 좋아했습니다: <%= message %></p>
                    <% when 'friend_like_reply'%>
                        <p><strong><%=username%></strong>님이 당신의 대댓글을 좋아했습니다: <%= message %></p>
                    <% when 'anonymous_like_article' %>
                        <p>누군가가 당신의 글을 좋아했습니다: <%= message %></p>
                    <% when 'anonymous_like_comment' %>
                        <p>누군가가 당신의 댓글을 좋아했습니다: <%= message %></p>
                    <% when 'anonymous_like_reply' %>
                        <p>누군가가 당신의 대댓글을 좋아했습니다: <%= message %></p>
                    <% else %>
                    <% end %>
                <% else %>
                    <% case noti.action %>
                    <% when 'friend_like_article' %>
                        <p><strong><%=username%></strong>님 외 <%= noti.origin.likes.size-1 %>명이 당신의 글을 좋아했습니다: <%= message %></p>
                    <% when 'friend_like_comment' %>
                        <p><strong><%=username%></strong>님 외 <%= noti.origin.likes.size-1 %>명이 당신의 댓글을 좋아했습니다: <%= message %></p>
                    <% when 'friend_like_reply' %>
                        <p><strong><%=username%></strong>님 외 <%= noti.origin.likes.size-1 %>명이 당신의 대댓글을 좋아했습니다: <%= message %></p>
                    <% when 'anonymous_like_article' %>
                        <p><%= noti.origin.likes.size %>명이 당신의 글을 좋아했습니다: <%= message %></p>
                    <% when 'anonymous_like_comment' %>
                        <p><%= noti.origin.likes.size %>명이 당신의 댓글을 좋아했습니다: <%= message %></p>
                    <% when 'anonymous_like_reply' %>
                        <p><%= noti.origin.likes.size %>명이 당신의 대댓글을 좋아했습니다: <%= message %></p>
                    <% else %>
                    <% end %>
                <% end %>   
            <% when 'Comment' %>
                <% message = "\"" + noti.origin.content.truncate(30, separator: /\s/) + "\"" %>
                <% if noti.action == 'friend_comment' %>
                    <% commenters_cnt = noti.origin.comments.named.distinct.count('author_id') %>
                    <% if !noti.origin.comments.named.where(author: current_user).empty? %>
                        <% commenters_cnt -= 1 %>
                    <% end %>
                    <% if commenters_cnt == 1 %>
                        <p><strong><%=username%></strong>님이 당신의 글 <%= message %>에 댓글을 남겼습니다.</p>
                    <% else %>
                        <p><p><strong><%=username%></strong>님 외 <%= commenters_cnt-1 %>명의 친구가 당신의 글 <%= message %>에 댓글을 남겼습니다.</p>
                    <% end %>
                <% elsif noti.action == 'anonymous_comment'%>
                    <% commenters_cnt = noti.origin.comments.anonymous.distinct.count('author_id') %>
                    <% if !noti.origin.comments.anonymous.where(author: current_user).empty? %>
                        <% commenters_cnt -= 1 %>
                    <% end %>
                    <% if commenters_cnt == 1 %>
                        <p>누군가가 당신의 글 <%= message %>에 익명댓글을 남겼습니다.</p>
                    <% else %>
                        <p><%= commenters_cnt %>명이 당신의 글 <%= message %>에 익명댓글을 남겼습니다.</p>
                    <% end %>
                <% end %>
            <% when 'Reply' %>
                <% message = "\"" + noti.origin.content.truncate(30, separator: /\s/) + "\"" %>
                <% case noti.action %>
                <% when 'anonymous_to_comment'%>
                    <% repliers_cnt = noti.origin.replies.anonymous.distinct.count('author_id') %>
                    <% if !noti.origin.replies.anonymous.where(author: current_user).empty? %>
                        <% repliers_cnt -= 1 %>
                    <% end %>
                    <% if repliers_cnt == 1 %>
                        <p>누군가가 당신의 익명댓글 <%= message %>에 대댓글을 남겼습니다.</p>
                    <% else %>
                        <p><%= repliers_cnt %>명이 당신의 익명댓글 <%= message %>에 대댓글을 남겼습니다.</p>
                    <% end%>
                <%# when 'anonymous_to_author'%>
                    <%# 누군가가 당신의 글에 대댓글을 남겼습니다. %>
                <% when 'friend_to_comment' %>
                    <% repliers_cnt = noti.origin.replies.named.distinct.count('author_id') %>
                    <% if !noti.origin.replies.named.where(author: current_user).empty? %>
                        <% repliers_cnt -= 1 %>
                    <% end %>
                    <% if repliers_cnt == 1 %>
                        <p><strong><%=username%></strong>님이 당신의 댓글에 대댓글을 남겼습니다.</p>
                    <% else %>
                        <p><strong><%=username%></strong>님 외 <%= repliers_cnt-1 %>명이 당신의 댓글에 대댓글을 남겼습니다.</p>
                    <% end %>
                <%# when 'friend_to_author' %>
                    <!--<%= username %>님이 당신의 글에 대댓글을 남겼습니다.-->
                <% when 'friend_to_recomment' %>
                    <% repliers_cnt = noti.origin.replies.where(target_author: current_user).distinct.count('author_id') %>
                    <% if !noti.origin.replies.where(target_author: current_user).where(author: current_user).empty? %>
                        <% repliers_cnt -= 1 %>
                    <% end %>
                    <% if repliers_cnt == 1 %>
                        <p><strong><%=username%></strong>님이 당신의 댓글에 대댓글을 남겼습니다.</p>
                    <% else %>
                        <p><strong><%=username%></strong>님 외 <%= repliers_cnt-1 %>명이 당신의 댓글에 대댓글을 남겼습니다.</p>
                    <% end %>
                <% else %>
                <% end %>
            <% when 'Drawer' %>
                <% message = "\"" + noti.origin.content.truncate(30, separator: /\s/) + "\"" %>
                <% if noti.origin.drawers.size == 1 %>
                    <p>당신의 글 <%= message %>이 누군가의 서랍장에 담겼습니다.</p>
                <% else %>
                    <p><%= noti.origin.drawers.size %>명이 당신의 글 <%= message %>을 서랍장에 담았습니다.</p>
                <% end %>
            <% when 'CustomQuestion' %>
                <% message = "\"" + noti.origin.content.truncate(30, separator: /\s/) + "\"" %>
                <% if CustomQuestion.where(ancestor_id: noti.origin.id).size == 1 %>
                    <p>누군가가 당신의 질문 <%= message %>을 리포스팅했습니다.</p>
                <% else %>
                    <p><%= CustomQuestion.where(ancestor_id: noti.origin.id).size %>명이 당신의 질문 <%= message %>을 리포스팅했습니다.</p>
                <% end %>
            <% when 'Assignment' %>
                <% case noti.action %>
                <% when 'assignment'%>
                    <% message = "\"" + noti.origin.content.truncate(30, separator: /\s/) + "\"" %>
                    <p><strong><%=username%></strong>님으로부터 새로운 질문이 도착했습니다: <%= message %></p>
                <% when 'custom-assignment'%>
                    <% message = "\"" + noti.origin.content.truncate(30, separator: /\s/) + "\"" %>
                    <p><strong><%=username%></strong>님으로부터 새로운 사용자 질문이 도착했습니다: <%= message %></p>
                <% else %>
                <% end %>
            <% when 'Answer' %>
                <% message = "\"" + noti.origin.question.content.truncate(30, separator: /\s/) + "\"" %>
                <p><strong><%=username%></strong>님이 당신이 보낸 질문 <%= message %>에 답했습니다.</p>
            <% when 'Friendship' %>
                <p><strong><%=username%></strong>님과 친구가 되었습니다.</p>
            <% when 'FriendRequest'%>
                <p><strong><%=username%></strong>님이 친구요청을 보냈습니다.</p>
            <% when 'Announcement' %>
                <% message = "\"" + noti.origin.title.truncate(30, separator: /\s/) + "\"" %>
                <% case noti.action %>
                <% when 'announcement'%>
                    <p>어도어에 새로운 공지가 있습니다: <%= message %></p>
                <% when 're_announcement' %>
                    <p>어도어에 당신의 소중한 의견을 남겨주세요.</p>
                <% else %>
                <% end %>
            <% when 'Highlight' %>
                <p><strong><%=username%></strong>님이 당신의 글을 highlight했습니다.</p>
            <% else %>  
            <% end %>
        </div>

        <div class = "date time">
            <%= time_tag noti.updated_at, class: "timeago" %>
        </div>

    </div>
<% end %>

app/views/notifications/index.html.erb
<div class = "inner-container">
    <%= render partial: "header" %>
    <% if noties.size > 0 %>
        <%= link_to "모두 읽음 표시", notification_read_all_path, id: "noti-index-read-text" %>
    <% end%>
    <%= render partial: "list", locals: {notifications: noties, from: "index"} %>
</div>

<script>
    $('body').trigger('click'); 
</script>