config/routes.rb
  # get '/custom_questions/:id/repost/edit' => 'custom_questions#repost_edit', as: :custom_question_repost_edit

  # Feed
  root 'feeds#friends'
  get '/feeds/general' => 'feeds#general', as: :general_feed

  # Question 
  get '/questions/today' => 'questions#today', as: :today_questions
  get '/questions/:id/friends' => 'questions#show_friends', as: :question_friends
  get '/questions/:id/general' => 'questions#show_general', as: :question_general
  get '/questions/import_all' => 'questions#import_all', as: :import_all_questions
  get '/questions/import_new' => 'questions#import_new', as: :import_new_questions
  resources :questions, only: [:index, :show]

  # Comment
  resources :comments, only: [:create, :destroy] 

  # Reply
  resources :replies, only: [:create, :destroy]

  # Like
  resources :likes, only: [:create, :destroy]
  get '/likes/:target_type/:target_id' => 'likes#likes_info'

  # Assignment
  get '/assignments' => 'assignments#index', as: :assignments
  get '/assignments/:question_id' => 'assignments#new', as: :new_assignment
  post '/assignments/:assignee_id/:question_id' => 'assignments#create', as: :create_assignment # get?
  delete '/assignments/:assignee_id/:question_id' => 'assignments#destroy', as: :destroy_assignment
  post '/assignments/:assignee_id/custom_question/:custom_question_id' => 'assignments#create_custom', as: :create_custom_assignment # get?
  delete '/assignments/:assignee_id/custom_question/:custom_uestion_id' => 'assignments#destroy_custom', as: :destroy_custom_assignment
  get '/assignments/custom_question/:custom_question_id' => 'assignments#new_custom', as: :new_custom_assignment

  # Drawer
  resources :drawers, only: [:create, :destroy]
  get '/drawers/:target_type/:target_id' => 'drawers#drawers_info'

  # Highlight
  resources :highlights, only: [:create, :destroy]

  # Notification
  get '/notifications' => 'notifications#index' , as: :notifications
  get '/notifications/read_all' => 'notifications#read_all', as: :notification_read_all
  get '/notifications/:id' => 'notifications#read'

  # Profile
  get '/profiles/:id' => 'profiles#index', as: :profile
  get '/profiles/:id/drawers' => 'profiles#drawers', as: :profile_drawers

  # User
  get '/users/:id/edit' => 'users#edit', as: :edit_user_profile
  patch '/users/:id/edit' => 'users#update', as: :update_user_profile
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', :confirmations => 'users/confirmations', :passwords => 'users/passwords', :sessions => 'users/sessions' }
  # 아래 코드는 이후에 멀티채널 구성에 맞추어 바뀌어야할수도.
  get '/users/friends' => 'users#friends', as: :friends
  put '/users/:id/image_upload' => 'users#image_upload', as: :image_upload
  # put '/users/:id/upload_image' => 'users#update', as: :upload_image
  post '/users/:id/add_friend' => 'users#add_friend', as: :add_friend # get?
  post '/users/:id/delete_friend' => 'users#delete_friend', as: :delete_friend
  # post '/users/:id/friend_request' => 'users#friend_request', as: :friend_request_send # get?
  
  # FriendRequest
  resources :friend_requests, only: [:destroy]
  get '/friend_requests' => 'friend_requests#index', as: :friend_requests
  post '/friend_requests/:id' => 'friend_requests#create', as: :friend_request_create
  put '/friend_requests/:id/deny' => 'friend_requests#deny', as: :friend_request_deny

  # Invitation
  get '/invitations' => 'invitations#index', as: :invitations
  get '/invitations/link' => 'invitations#link', as: :invitation_link
  get '/invitations/:id(/:question_id1(/:question_id2(/:question_id3)))' => 'invitations#accept', as: :invitation_accept

  # Search
  get '/search/all' => 'search#all', as: :search_all
  get '/search/admin_question' => 'search#admin_question', as: :search_admin_question
  get '/search/custom_question' => 'search#custom_question', as: :search_custom_question
  get '/search/user' => 'search#user', as: :search_user

  # Channel
  resources :channels, only: [:create, :update, :destroy]
  put '/channels/:id/edit_friendship' => 'channels#edit_friendship'

  # Announcement
  resources :announcements, only: [:create, :update, :destroy]
  get '/announcements' => 'announcements#index', as: :announcement_index
  get '/announcements/admin'  => 'announcements#admin_index', as: :announcement_admin_index
  get '/announcements/:id/publish' => 'announcements#publish', as: :announcement_publish
  get '/announcements/:id/noti' => 'announcements#noti', as: :announcement_noti

  # User Stats
  get '/stats/daily' => 'stats#daily', as: :daily_stats
  get '/stats/monthly' => 'stats#monthly', as: :monthly_stats
  
  namespace 'api' do
    namespace 'v1', defaults: { format: :json } do
      
      # Sessions
      resource :sessions, only: [:create, :destroy, :show] # delete request가 실제로 user을 delete하는 것이 아니기 때문에 resources가 아니라 resource로 두는 것이 맞습니다. 고치지 말아주세요!
      resources :users, only: [:create] 

      # Answer
      resources :answers, except: [:new]
      get '/answers/:id/new' => 'answers#new', as: :new_answer
      get '/answers/:id/friend_comments' => 'answers#friend_comments'
      get '/answers/:id/general_comments' => 'answers#general_comments'
      get '/answers/:id/likes' => 'answers#likes'

      # Post
      resources :posts, except: [:new]
      get '/posts/:id/friend_comments' => 'posts#friend_comments'
      get '/posts/:id/general_comments' => 'posts#general_comments'
      get '/posts/:id/likes' => 'posts#likes'

      # CustomQuestion
      resources :custom_questions, only: [:show, :create, :destroy, :update, :edit]
      post '/custom_questions/:id/repost' => 'custom_questions#repost_create', as: :custom_question_repost_form
      get '/custom_questions/:id/repost' => 'custom_questions#repost_new', as: :custom_question_repost
      get '/custom_questions/:id/friend_comments' => 'custom_questions#friend_comments'
      get '/custom_questions/:id/general_comments' => 'custom_questions#general_comments'
      get '/custom_questions/:id/likes' => 'custom_questions#likes'

      # Feed
      root 'feeds#friends'
      get '/feeds/general' => 'feeds#general', as: :general_feed

      # Question
      get '/questions/today' => 'questions#today', as: :today_questions
      get '/questions/:id/friends' => 'questions#show_friends', as: :question_friends
      get '/questions/:id/general' => 'questions#show_general', as: :question_general
      get '/questions/import_all' => 'questions#import_all', as: :import_all_questions
      get '/questions/import_new' => 'questions#import_new', as: :import_new_questions
      resources :questions, only: [:index, :show]

      # Comment
      resources :comments, only: [:create, :destroy]

      # Reply
      resources :replies, only: [:create, :destroy]

      # Like
      resources :likes, only: [:create, :destroy]
      get '/likes/:target_type/:target_id' => 'likes#likes_info'

      # Assignment
      get '/assignments' => 'assignments#index', as: :assignments

      get '/assignments/:question_id' => 'assignments#new', as: :new_assignment 
      post '/assignments/:assignee_id/:question_id' => 'assignments#create', as: :create_assignment # get?
      delete '/assignments/:assignee_id/:question_id' => 'assignments#destroy', as: :destroy_assignment
      
      post '/assignments/:assignee_id/custom_question/:custom_question_id' => 'assignments#create_custom', as: :create_custom_assignment # get?
      delete '/assignments/:assignee_id/custom_question/:custom_uestion_id' => 'assignments#destroy_custom', as: :destroy_custom_assignment
      get '/assignments/custom_question/:custom_question_id' => 'assignments#new_custom', as: :new_custom_assignment  

      # Drawer
      resources :drawers, only: [:create, :destroy]
      get '/drawers/:target_type/:target_id' => 'drawers#drawers_info'

      # Highlight
      resources :highlights, only: [:create, :destroy]

      # Notification
      get '/notifications/read_all' => 'notifications#read_all', as: :notification_read_all
      get '/notifications/:id' => 'notifications#read'
      get '/notifications/all/index' => 'notifications#index' , as: :notification_index 

      # Profile
      get '/profiles/:id' => 'profiles#index', as: :profile
      get '/profiles/:id/drawers' => 'profiles#drawers', as: :profile_drawers

      # User
      get '/users/:id/edit' => 'users#edit', as: :edit_user_profile
      patch '/users/:id/edit' => 'users#update', as: :update_user_profile
      # devise_for :users, :controllers => {:confirmations => 'users/confirmations', omniauth_callbacks: 'user/omniauth_callbacks' }
      devise_for :users, :controllers => {:confirmations => 'users/confirmations' }
      # 아래 코드는 이후에 멀티채널 구성에 맞추어 바뀌어야할수도.
      get '/users/friends' => 'users#friends', as: :friends
      put '/users/:id/image_upload' => 'users#image_upload', as: :image_upload
      # put '/users/:id/upload_image' => 'users#update', as: :upload_image
      post '/users/:id/add_friend' => 'users#add_friend', as: :add_friend # get?
      post '/users/:id/friend_request' => 'users#friend_request', as: :friend_request # get?
      

      # Invitation
      get '/invitations' => 'invitations#index', as: :invitation
      get '/invitations/link' => 'invitations#link', as: :invitation_link
      get '/invitations/:id(/:question_id1(/:question_id2(/:question_id3)))' => 'invitations#accept', as: :invitation_accept

      # Search
      get '/search/all' => 'search#all', as: :search_all
      get '/search/admin_question' => 'search#admin_question', as: :search_admin_question
      get '/search/custom_question' => 'search#custom_question', as: :search_custom_question
      get '/search/user' => 'search#user', as: :search_user

      # Channel
      resources :channels, only: [:create, :update, :destroy]
      put '/channels/:id/edit_friendship' => 'channels#edit_friendship'

      # Announcement
      resources :announcements, only: [:create, :update, :destroy]

app/controllers/api/v1/invitations_controller.rb
class Api::V1::InvitationsController < ApplicationController
  before_action :authenticate_user!, except: [:accept]

  def index
    @questions = []
    if (n = (7 - @questions.length)) > 0
      @questions = Question.published.sample(n) # 답변된 질문이 부족하면 공개된 질문 중 랜덤하게 take
    end

    # render :index, locals: { questions: @questions }
  end

  def link
    assigned_questions = [] # 선택된 question들을 갖고 있다 (최대 3개, 최소 0개)
    assigned_questions = Question.find(params[:q]) if params[:q]
    if Rails.env.production?
      @link = "https://adoor.app/invitations/#{current_user.id}"
    elsif Rails.env.development?
      @link = "localhost:3000/invitations/#{current_user.id}"
    end
    assigned_questions.each do |q|
      @link += '/' + q.id.to_s
    end
    @link += '/' + 'empty' if assigned_questions.empty?
    # now the link looks like ".../invitations/:user_id/:qid1/:qid2/:qid3" (qid's are optional)
    
    # render :link
    render json: {status: 'SUCCESS', message:'Created invitation link', data: @link}, status: :ok
  end

  def accept
    @new_friend = User.find(params[:id])
    @assigned_questions = []
    if params[:question_id1] != 'empty'
      @assigned_questions.push(Question.find(params[:question_id1])) # empty도 아니면서 question_id 가 하나도 없는 경우는 잘못된 링크이므로 이걸 걸러내기 위해
      @assigned_questions.push(Question.find(params[:question_id2])) if params[:question_id2]
      @assigned_questions.push(Question.find(params[:question_id3])) if params[:question_id3]

      if !user_signed_in?
      # session[:invitation] = request.referer
      elsif current_user.id == @new_friend.id
      elsif current_user.friends.include? @new_friend
        @assigned_questions.each do |q|
          Assignment.find_or_create_by(question_id: q.id, assigner_id: @new_friend.id, assignee_id: current_user.id)
        end
      else
        @assigned_questions.each do |q|
          # assigner가 admin인 assignment 만들기
          # 이 경우 noti는 생성이 안되지만, assignment는 생성됨. 즉, assignment 모아보는 페이지에서는 이 질문들이 보임!(그럴 예정)
          Assignment.find_or_create_by(question_id: q.id, assigner_id: 1, assignee_id: current_user.id)
        end
      end
    end

    # render :accept, locals: { new_friend: @new_friend, assigned_questions: @assigned_questions }

    # private

    # def authenticate_user
    #   user_token = request.headers['X-USER-TOKEN']
    #   if user_token
    #     @user = User.find_by_token(user_token)
    #     #Unauthorize if a user object is not returned
    #     if @user.nil?
    #       return unauthorize
    #     end
    #   else
    #     return unauthorize
    #   end
    # end

    # def unauthorize
    #   head status: :unauthorized
    #   return false
    # end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
    before_action :authenticate_user!, except: [:accept]

    def index
        @questions = []
        if (n = (7 - @questions.length)) > 0
            @questions = Question.published.sample(n) # 답변된 질문이 부족하면 공개된 질문 중 랜덤하게 take
        end
        render 'index' 
    end 

    def link
        assigned_questions = []   # 선택된 question들을 갖고 있다 (최대 3개, 최소 0개)
        assigned_questions = Question.find(params[:q]) if params[:q]
        if Rails.env.production?
            @link = "https://adoor.app/invitations/#{current_user.id}"
        elsif Rails.env.development?
            @link = "localhost:3000/invitations/#{current_user.id}"
        end
        assigned_questions.each do |q|
            @link += "/" + q.id.to_s
        end
        if assigned_questions.empty?
            @link += "/" + "empty"
        end
        # now the link looks like ".../invitations/:user_id/:qid1/:qid2/:qid3" (qid's are optional)
        render 'link'
    end

    def accept
        @new_friend = User.find(params[:id])
        @assigned_questions = []
        if params[:question_id1] != "empty"
            @assigned_questions.push(Question.find(params[:question_id1])) # empty도 아니면서 question_id 가 하나도 없는 경우는 잘못된 링크이므로 이걸 걸러내기 위해
            @assigned_questions.push(Question.find(params[:question_id2])) if params[:question_id2]
            @assigned_questions.push(Question.find(params[:question_id3])) if params[:question_id3]

            # assign 모델 생기는 거 그냥 없애버렸음!!
            # if !user_signed_in?
            #     #session[:invitation] = request.referer
            # elsif current_user.id == @new_friend.id
            # elsif current_user.friends.include? @new_friend
            #     @assigned_questions.each do |q|
            #         Assignment.find_or_create_by(question_id: q.id, assigner_id: @new_friend.id, assignee_id: current_user.id)
            #     end
            # else
            #     @assigned_questions.each do |q|
            #         # assigner가 admin인 assignment 만들기
            #         # 이 경우 noti는 생성이 안되지만, assignment는 생성됨. 즉, assignment 모아보는 페이지에서는 이 질문들이 보임!(그럴 예정)
            #         Assignment.find_or_create_by(question_id: q.id, assigner_id: 1, assignee_id: current_user.id)
            #     end
            # end
        end
        render 'accept'
    end
end

app/helpers/api/v1/invitations_helper.rb
module Api::V1::InvitationsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/accept.html.erb
<div class="inner-container">
    <div class = "prism-box">
        <div class  = "prism-box__content">
            <% if @new_friend == current_user %>
                <div class="invitation-accept-text">
                    친구에게 초대링크를 보내보세요!
                </div> 
            <% else %>
                <% if @assigned_questions.empty? %>
                    <div class="invitation-accept-text">
                        <% if !user_signed_in? %>
                            <%= @new_friend.username %>님이 당신을 어도어에 초대했어요!<br>
                            로그인 또는 회원가입 후 <%= @new_friend.username %>님과 친구가 되어보세요.<br><br><br>
                    </div>
                        <div class="desktop-question">
                            <button class="orange-btn"><%= link_to '로그인', new_user_session_path, style: "color: white;"%></button>
                            <button class="white-btn"><%= link_to '회원가입', new_user_registration_path, style: "color: gray;"%></button><br>
                        </div>
                        <% elsif !current_user.friends.include? @new_friend %>
                            <% if user_signed_in? && (!current_user.friends.include? @new_friend) %>
                                <% if FriendRequest.where(requester_id: @new_friend.id, requestee_id: current_user.id).exists? %>
                                    <div class="invitation-accept-text"><%= @new_friend.username %>님이 친구요청을 보냈어요.</div>
                                    <%= link_to "친구수락", add_friend_path(@new_friend.id), method: :post, id: "friends-btn" %><br><br>
                                <% elsif FriendRequest.where(requester_id: current_user.id, requestee_id: @new_friend.id).exists? %>
                                    <div class="invitation-accept-text"><%= @new_friend.username %>님에게 친구요청을 보냈습니다.</div>
                                    <% fr_id = FriendRequest.where(requester_id: current_user.id, requestee_id: @new_friend.id).first.id%>
                                    <%= link_to "친구요청 취소", friend_request_path(fr_id), method: :delete, id: "friends-btn" %><br><br>
                                <% else %>
                                    <div class="invitation-accept-text"><%= @new_friend.username %>님과 친구가 되어보세요.</div>
                                    <%= link_to "친구요청", friend_request_create_path(@new_friend.id), method: :post, id: "friends-btn" %><br><br>
                                <% end %>
                            <% end %>
                        <% else %>
                            <div class="invitation-accept-text"><%= @new_friend.username %>님과 이미 친구입니다.</div>
                            <%= link_to "친구 페이지 가기", profile_path(@new_friend.slug), method: :get, id: "friends-btn" %>
                        <% end%>
                    </div>
                <% else %> 
                    
                    <div class="prism-title" style="padding-top: 10px;"><h3><%= @new_friend.username %>님이 보낸 질문</h3></div>

                    <div class="invitation-accept-text">
                        <% if !user_signed_in? %>
                            <%= @new_friend.username %>님이 당신을 어도어에 초대했어요!<br><br>
                            로그인 또는 회원가입 후 <%= @new_friend.username %>님과 친구가 되어보세요.<br><br><br>
                    </div>
                        <div class="desktop-question">
                            <button class="orange-btn"><%= link_to '로그인', new_user_session_path, style: "color: white;"%></button>
                            <button class="white-btn"><%= link_to '회원가입', new_user_registration_path, style: "color: gray;"%></button><br>
                        </div>
                        <% elsif !current_user.friends.include? @new_friend %>
                            <% if FriendRequest.where(requester_id: @new_friend.id, requestee_id: current_user.id).exists? %>
                                <div class="invitation-accept-text"><%= @new_friend.username %>님이 친구요청을 보냈어요.</div>
                                <%= link_to "친구수락", add_friend_path(@new_friend.id), method: :post, id: "friends-btn" %>
                            <% elsif FriendRequest.where(requester_id: current_user.id, requestee_id: @new_friend.id).exists? %>
                                <div class="invitation-accept-text"><%= @new_friend.username %>님에게 친구요청을 보냈습니다.</div>
                                <% fr_id = FriendRequest.where(requester_id: current_user.id, requestee_id: @new_friend.id).first.id %>
                                <%= link_to "친구요청 취소", friend_request_path(fr_id), method: :delete, id: "friends-btn" %>
                            <% else %>
                                <div class="invitation-accept-text"><%= @new_friend.username %>님과 친구가 되어보세요.</div>
                                <%= link_to "친구요청", friend_request_create_path(@new_friend.id), method: :post, id: "friends-btn" %><br><br>
                            <% end %>
                        <% else %>
                            <div class="invitation-accept-text"><%= @new_friend.username %>님과 이미 친구입니다.</div>
                            <%= link_to "친구 페이지 가기", profile_path(@new_friend.slug), method: :get, id: "friends-btn" %><br><br>
                        <% end %>
                    <div class="desktop-question">
                        <hr>
                    </div>
                <% end %>
            <% end %>
        </div>
        <div class="desktop-question">
            <%= render partial: "questions/layout", locals: { questions: @assigned_questions} %><br/>
        </div>
    </div>
</div>
<div class="mobile-question">
    <% if !user_signed_in? %>
        <button class="orange-btn"><%= link_to '로그인', new_user_session_path, style: "color: white;"%></button>
        <button class="white-btn"><%= link_to '회원가입', new_user_registration_path, style: "color: gray;"%></button><br>
    <% end %>
    
    <%= render partial: "questions/layout", locals: { questions: @assigned_questions} %><br/>
</div>

app/views/invitations/index.html.erb
<div class = "inner-container">
    <div class = "prism-box">
        <div class  = "prism-box__content">
        <%# <h1 class = "prism-title">친구 초대하기</h1> %>
            <div class="link-generation-box">
                <div class="link-generation-text">
                    친구에게 초대링크를 보내보세요.<br>
                    최대 3개의 질문과 함께 보낼 수 있어요!<br>
                </div>
                <%= form_tag(invitation_link_path, method: :get, class: "invitation-form") do %>
                    <% @questions.each do |question| %>
                        <%= check_box_tag "q[]", question.id, false, id: question.id.to_s%>
                        <%= label_tag "#{question.id}", question.content %><br><br>
                    <% end %>
                    <%= button_tag "링크 생성하기", class: "link-generation-btn" %><br>
                <% end %>
            </div>               
        </div>
    </div>
</div>


<script>

$(document).ready(function() {

    var limit = 3;
    $('input[name="q[]"]').on('change', function(evt) {
        if($(this).siblings(':checked').length >= limit) {
            this.checked = false;
            alert("질문은 3개까지만 선택할 수 있어요!");
        }
    });
});

</script>

app/views/invitations/link.html.erb
<div class = "inner-container">
    <div class = "invitation-link-box">
        <div class = "invitation-link-content">
            <h1 class = "invitation-link-title">초대장</h1>
            <br>
            <br>
            <input type="text" value= "<%= @link %>" id="myInput">
            <button onclick="myFunction()" onmouseout="outFunc()" >클립보드에 복사하기</button>
        </div>
        <br>
        <br>
        <div>
            생성된 링크를 친구에게 보내보세요.<br>
            친구가 링크로 접속하면 (회원가입 후) <%= current_user.username %>님에게 친구요청을 보낼 수 있어요.
        </div>
    </div>


<script>
// 참고: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_copy_clipboard2
function myFunction() {
    var copyText = document.getElementById("myInput");
    copyText.select();
    document.execCommand("copy");

    var tooltip = document.getElementById("myTooltip");
    tooltip.innerHTML = "클립보드에 복사되었습니다!";
    }

function outFunc() {
    var tooltip = document.getElementById("myTooltip");
    tooltip.innerHTML = "클립보드에 복사하기";
}

</script>